spring:
  application:
    name: internmatch
 
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/internmatch?useSSL=false&serverTimezone=Asia/Manila&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:internmatch}
    driver-class-name: com.mysql.cj.jdbc.Driver
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
 
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
 
server:
  port: ${SERVER_PORT:8081}
 
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
 
app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  oauth2:
    frontend-redirect-url: ${FRONTEND_REDIRECT_URL:http://localhost:5173/oauth-callback}